/**
 * @file dialect.h
 * @brief Picceler MLIR dialect declarations.
 *
 * This header includes piccelerDialect.h.inc, which is generated by MLIR
 * TableGen during the build. It must not be edited manually.
 */
#pragma once

#include "mlir/IR/Dialect.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/DialectImplementation.h"

#include "piccelerDialect.h.inc"