/**
 * @file types.h
 * @brief Picceler MLIR type declarations, it includes piccelerTypes.h.inc, which is generated by MLIR
 * TableGen during the build. It must not be edited manually.
 */

#pragma once

#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/TypeSupport.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/TypeSwitch.h"

#define GET_TYPEDEF_CLASSES
#include "piccelerTypes.h.inc"
#undef GET_TYPEDEF_CLASSES